#index:
  #path: /
  #controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Application\Http\Controller\HomeController

healthcheck:
  path: /healthcheck
  controller: App\Application\Http\Controller\HealthCheckController
