#index:
  #path: /
  #controller: App\Controller\DefaultController::index

index:
  path: /
  controller: Statistico\Auth\Application\Http\HomeController

healthcheck:
  path: /healthcheck
  controller: Statistico\Auth\Application\Http\HealthCheck\Controller\HealthCheckController
