# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.host: '%env(string:APP_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Statistico\Auth\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Statistico\Auth\Application\Http\HealthCheck\Controller\:
        resource: '../src/Application/Http/HealthCheck/Controller'
        tags: ['controller.service_arguments']

    Statistico\Auth\Application\Http\:
        resource: '../src/Application/Http'
        tags: ['controller.service_arguments']

    Statistico\Auth\Application\Http\ApiV1\User\Controller\:
        resource: '../src/Application/Http/ApiV1/User/Controller'
        tags: ['controller.service_arguments']

    # Console commands
    Statistico\Auth\Application\Console\User\UserCreateCommand:
        tags:
            - { name: 'console.command', command: 'user:create' }

    # Event Listeners
    Statistico\Auth\Framework\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Statistico\Auth\Domain\User\Persistence\UserRepository:
        alias: 'Statistico\Auth\Domain\User\Persistence\DatabaseUserRepository'
        public: true

    Statistico\Auth\Domain\Subscription\Betting\Persistence\BettingSubscriptionRepository:
        alias: 'Statistico\Auth\Domain\Subscription\Betting\Persistence\DatabaseBettingSubscriptionRepository'

    Statistico\Auth\Framework\Time\Clock:
        alias: 'Statistico\Auth\Framework\Time\SystemClock'
        public: true
