<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6xJ5UB\Statistico_Auth_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6xJ5UB/Statistico_Auth_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerC6xJ5UB.legacy');

    return;
}

if (!\class_exists(Statistico_Auth_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerC6xJ5UB\Statistico_Auth_KernelTestDebugContainer::class, Statistico_Auth_KernelTestDebugContainer::class, false);
}

return new \ContainerC6xJ5UB\Statistico_Auth_KernelTestDebugContainer([
    'container.build_hash' => 'C6xJ5UB',
    'container.build_id' => '5eb7c9c9',
    'container.build_time' => 1578415327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6xJ5UB');
