<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMwmLpDe\Statistico_Auth_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMwmLpDe/Statistico_Auth_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMwmLpDe.legacy');

    return;
}

if (!\class_exists(Statistico_Auth_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMwmLpDe\Statistico_Auth_KernelDevDebugContainer::class, Statistico_Auth_KernelDevDebugContainer::class, false);
}

return new \ContainerMwmLpDe\Statistico_Auth_KernelDevDebugContainer([
    'container.build_hash' => 'MwmLpDe',
    'container.build_id' => 'e5b69b52',
    'container.build_time' => 1578415353,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMwmLpDe');
